---
name: Publish Test Results
on:
  workflow_run:
    workflows: [Test code]
    types: [completed]
  workflow_call:
jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.workflow_run.event.name }}
          echo ${{ github.event.workflow_run.event }}
  publish-test-results:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event.name == 'pull_request' && !contains(fromJSON('["skipped", "cancelled"]'), github.event.workflow_run.conclusion) }}
    strategy:
      fail-fast: false
      matrix:
        os_name: [ubuntu, windows, macos]
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*artifact_${{ matrix.os_name }}_tests*'
          path: artifacts
      - name: Publish Test Results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-results-${{ matrix.os_name }}
          number: ${{ github.event.workflow_run.event.number }}
          recreate: true
          path: artifacts/artifact_${{ matrix.os_name }}_tests/.results_tests/github_report.md
      - name: Add workflow link to comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-results-${{ matrix.os_name }}
          number: ${{ github.event.workflow_run.event.number }}
          append: true
          message: |-
            <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}">Link to workflow run</a></p>
