---
name: Publish Test Results
on:
  workflow_run:
    workflows: [Test code]
    types: [completed]
  workflow_call:
jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event.name == 'pull_request' && !contains(fromJSON('["skipped", "cancelled"]'), github.event.workflow_run.conclusion) }}
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Publish Test Results
        id: test-results
        uses: mikepenz/action-junit-report@v4
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: artifacts/**/.results_tests/results.xml
          check_name: Test Results
          require_tests: true
          update_check: true
          check_annotations: true
          annotate_only: true
          job_summary: true
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-results
          number: ${{ github.event.workflow_run.event.number }}
          message: |-
            <h1>Test Results</h1>
            <table>
            <tr>
            <th>Tests</th>
            <th>Passed &#x2705;</th>
            <th>Skipped &#x23ED;</th>
            <th>Failed &#x274C;</th>
            </tr>
            <tr>
            <td>${{ steps.test-results.outputs.total }} ran</td>
            <td>${{ steps.test-results.outputs.passed }} passed</td>
            <td>${{ steps.test-results.outputs.skipped }} skipped</td>
            <td>${{ steps.test-results.outputs.failed }} failed</td>
            </tr>
            <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" target="_blank">Workflow run</a></p>
            </table>
