---
name: Publish Test Results
on:
  workflow_run:
    workflows: [Test code123]  # TODO: update to just "Test code"
    types: [completed]
  workflow_call:
jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write
      pull-requests: write
      actions: read
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: artifacts/**/.results_*/results.xml
          large_files: true
          report_individual_runs: true
          action_fail_on_inconclusive: true
