---
name: Publish Test Results Testing
on:
  workflow_run:
    workflows: [Test code]
    types: [completed]
jobs:
  publish-test-results:
    permissions:
      checks: write
      pull-requests: write
      actions: read
    uses: ./.github/workflows/publish-test-results.yml
