---
name: Update python linting dependencies in-sync with pre-commit
on:
  pull_request:
    branches: [main]
jobs:
  update-python-and-pre-commit-deps:
    name: Update python linters and pre-commit dependencies
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'nfelt14'  # TODO: change to dependabot
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TEK_OPENSOURCE_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: x  # any version
          check-latest: true
      - name: Install workflow dependencies
        run: pip install poetry yamlfix toml-sort requests pre-commit-update
      - name: Configure git
        run: |
          git config --system --add safe.directory "*"
          git config user.name "${{ vars.TEK_OPENSOURCE_NAME }}"
          git config user.email "${{ vars.TEK_OPENSOURCE_EMAIL }}"
          mkdir --parents ~/.ssh
          echo -e "${{ secrets.TEK_OPENSOURCE_SSH_SIGNING_KEY_PRIVATE }}" >>~/.ssh/signing_key
          cat ~/.ssh/signing_key
          echo -e "${{ secrets.TEK_OPENSOURCE_SSH_SIGNING_KEY_PUBLIC }}" >>~/.ssh/signing_key.pub
          cat ~/.ssh/signing_key.pub
          chmod 600 ~/.ssh/signing_key && chmod 600 ~/.ssh/signing_key.pub
          eval "$(ssh-agent)"
          ssh-add ~/.ssh/signing_key
          git config gpg.format ssh
          git config user.signingKey ~/.ssh/signing_key
          git config commit.gpgsign true
          touch ~/.ssh/allowed_signers
          echo "${{ vars.TEK_OPENSOURCE_EMAIL }} ${{ secrets.TEK_OPENSOURCE_SSH_SIGNING_KEY_PUBLIC }}" >~/.ssh/allowed_signers
          git config gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers
      - name: Run updater script
        run: python scripts/update_development_dependencies.py --no-install
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Update python linters and pre-commit dependencies.'
          commit_user_name: ${{ vars.TEK_OPENSOURCE_NAME }}
          commit_user_email: ${{ vars.TEK_OPENSOURCE_EMAIL }}
          commit_author: ${{ vars.TEK_OPENSOURCE_NAME }} <${{ vars.TEK_OPENSOURCE_EMAIL }}>
