---
name: Update python linting dependencies in-sync with pre-commit
on:
  pull_request:
    branches: [main]
jobs:
  update-python-and-pre-commit-deps:
    name: Update python linters and pre-commit dependencies
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'nfelt14'  # TODO: change to dependabot
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: x  # any version
          check-latest: true
      - name: Install workflow dependencies
        run: pip install poetry yamlfix requests pre-commit-update
      - name: Print Information
        run: |-
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.user.login }}
      - name: Run updater script
        run: python scripts/update_development_dependencies.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Update python linters and pre-commit dependencies.'
