---
name: Update python linting dependencies in-sync with pre-commit
on:
  pull_request:
    branches: [main]
jobs:
  update-python-and-pre-commit-deps:
    name: Update python linters and pre-commit dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: x  # any version
          check-latest: true
      - name: Install workflow dependencies
        run: pip install poetry-core yamlfix
      - name: Print Information
        run: |-
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.user.login }}
